// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFpyaqjgNJLNyGA6ICpmxfpMFdTWoDMzw',
    appId: '1:366844379597:web:64d586bb76a598acf74484',
    messagingSenderId: '366844379597',
    projectId: 'pocket-clinic-95e40',
    authDomain: 'pocket-clinic-95e40.firebaseapp.com',
    storageBucket: 'pocket-clinic-95e40.appspot.com',
    measurementId: 'G-F96D7322QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx_sBCTAZAKStAqOb-3mSd0mDn3JKPLWw',
    appId: '1:366844379597:android:7a468744b14fb8acf74484',
    messagingSenderId: '366844379597',
    projectId: 'pocket-clinic-95e40',
    storageBucket: 'pocket-clinic-95e40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwVNELt-DXSgt80Wa0tzCqUMvtgZR3Gcs',
    appId: '1:366844379597:ios:e222a9eaf8ff61e8f74484',
    messagingSenderId: '366844379597',
    projectId: 'pocket-clinic-95e40',
    storageBucket: 'pocket-clinic-95e40.appspot.com',
    iosBundleId: 'com.example.pocketClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwVNELt-DXSgt80Wa0tzCqUMvtgZR3Gcs',
    appId: '1:366844379597:ios:e222a9eaf8ff61e8f74484',
    messagingSenderId: '366844379597',
    projectId: 'pocket-clinic-95e40',
    storageBucket: 'pocket-clinic-95e40.appspot.com',
    iosBundleId: 'com.example.pocketClinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFpyaqjgNJLNyGA6ICpmxfpMFdTWoDMzw',
    appId: '1:366844379597:web:32b38dea4a129563f74484',
    messagingSenderId: '366844379597',
    projectId: 'pocket-clinic-95e40',
    authDomain: 'pocket-clinic-95e40.firebaseapp.com',
    storageBucket: 'pocket-clinic-95e40.appspot.com',
    measurementId: 'G-15BSP2SX6H',
  );
}
